services:
  postgres:
    container_name: citadel_postgres
    image: 'postgres:13'
    ports:
      - '5432:5432'
    environment:
      PGPASSWORD: citadel
      POSTGRES_DB: citadel
      POSTGRES_USER: citadel
      POSTGRES_PASSWORD: citadel
    volumes:
      - 'citadel_postgres:/var/lib/postgresql/data'

  reverse-proxy:
    image: traefik:v2.10
    command:
      - '--api.insecure=true'
      - '--providers.docker'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      - '--certificatesresolvers.myresolver.acme.httpchallenge=true'
      - '--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web'
      - '--certificatesresolvers.myresolver.acme.email=contact@softwarecitadel.com'
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - './letsencrypt:/letsencrypt'
    networks:
      - traefik

  whoami:
    image: traefik/whoami
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.whoami.rule=Host(`whoami.softwarecitadel.app`)'
      - 'traefik.http.routers.whoami.entrypoints=websecure'
      - 'traefik.http.routers.whoami.tls.certresolver=myresolver'
    networks:
      - traefik

  redis:
    image: redis:6.2
    container_name: citadel_redis
    ports:
      - '6379:6379'

volumes:
  citadel_postgres:

networks:
  traefik:
